Promise.reject('Error occurred').catch(err => console.log(err));